### ISSUE TITLE
how to evaluate the performance on test set?

### ISSUE THREAD

**Issue by xwjBupt** [Media-Smart/vedadet#30]
Hi! 

     thanks for sharing the code, but i do not understand how to evaluate on test set as there is no '.txt' file in test set? how should i modify the tinaface.py？ thank you so much!!

**Comment by mike112223** [comment]
Please refer to http://shuoyang1213.me/WIDERFACE/index.html. You have to evaluate the test images and submit detection results.

**Comment by xwjBupt** [comment]
yes, i understand i need to submit prediction result on test set to evaluate the performace, but how can i get the prediction results on test set? There is only the code of tinaface for validation set, not for test set?

**Comment by mike112223** [comment]
Hi,
We do not provide the code for test evaluation since it's easy to implement. The evaluation of test and val sets are almost the same, and the only difference is that you should create a new dataset to only pass the image (like infer.py). And then again by running test_widerface.py you can get the xml files for evaluation.

**Comment by xwjBupt** [comment]
OK, I understand, thank you so much!!
