### ISSUE TITLE
Facing issue when running "pip install -v -e ." on windows machine 

### ISSUE THREAD

**Issue by kiranbab** [Media-Smart/vedadet#56]
Facing issue when running "pip install -v -e ." on windows machine
config{
windows:10
cuda 10.2
python:3.8}

![image](https://user-images.githubusercontent.com/12935746/120808063-4c28a400-c566-11eb-9a72-9696f6024fd1.png)

**Comment by Sahel13** [comment]
Updating pip worked for me.
`python -m pip install --upgrade pip`

**Comment by darjazafirovic** [comment]
As explained here https://forums.developer.nvidia.com/t/strange-link-error-seen-by-multiple-people-while-building-pytorch-cpp-cuda-extensions/145261/2 the issue happens because long resolves to 32-bit int on Windows as opposed to 64-bit long long on Linux. Replace the two occurrences of long in sigmoid_focal_loss_cuda.cu with int64_t and it will work fine.
