### ISSUE TITLE
ImportError: cannot import name 'deform_conv_ext'

### ISSUE THREAD

**Issue by gmt710** [Media-Smart/vedadet#8]
Greatly thank for your sharing.
when I run the command:
```
tools/dist_trainval.sh configs/trainval/tinaface/tinaface.py "0,1,2,3"
```
I met this problem:
```
ImportError: cannot import name 'deform_conv_ext'
```
Maybe this cause by dcn, Would you mind giving some suggestions for me?
Thx.

**Comment by hxcai** [comment]
@gmt710 Have you installed vedadet as following?
pip install -r requirements/build.txt
pip install -v -e .

**Comment by gmt710** [comment]
Yeah, I'll try again.

**Comment by gmt710** [comment]
Can I use torch==1.1.0 ? Because my cuda version is 9.0.

**Comment by gmt710** [comment]
@hxcai ,Hello, it do not include the file vedadet/ops/dcn/src/deform_conv_ext.cpp

**Comment by hxcai** [comment]
@gmt710 we recommend using torch==1.6.0 or higher.

**Comment by gmt710** [comment]
@hxcai ,thanks for your reply.My enviroment ,cuda9.2 torch1.6.0 test good.
I have another problem about how to prepare widerface datasets for train and test ?
Refers the code comments and the bugs, I prepare widerface data but test and train are not working properly.
![image](https://user-images.githubusercontent.com/34018741/100840843-6e574180-34b1-11eb-9ed3-79a6ff83b0e0.png)

**Comment by Kerr46** [comment]
Thank you for your sharing.
But I have this issue,too.  I don't know how  to figure it out.

ImportError: cannot import name 'deform_conv_ext'

I have try this :
pip install -r requirements/build.txt
pip install -v -e .

But I've got :

Using pip 20.2.4 from /home/cv/anaconda3/envs/tinaface/lib/python3.7/site-packages/pip (python 3.7)
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-l6jhmr6r
Created temporary directory: /tmp/pip-req-tracker-mxmsm8pp
Initialized build tracking at /tmp/pip-req-tracker-mxmsm8pp
Created build tracker: /tmp/pip-req-tracker-mxmsm8pp
Entered build tracker: /tmp/pip-req-tracker-mxmsm8pp
Created temporary directory: /tmp/pip-install-yi04rbse
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///home/cv/PycharmProjects/vedadet
  Added file:///home/cv/PycharmProjects/vedadet to build tracker '/tmp/pip-req-tracker-mxmsm8pp'
    Running setup.py (path:/home/cv/PycharmProjects/vedadet/setup.py) egg_info for package from file:///home/cv/PycharmProjects/vedadet
    Created temporary directory: /tmp/pip-pip-egg-info-63ncdptk
    Running command python setup.py egg_info
    /home/cv/anaconda3/envs/tinaface/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  /opt/conda/conda-bld/pytorch_1603729138878/work/c10/cuda/CUDAFunctions.cpp:100.)
      return torch._C._cuda_getDeviceCount() > 0
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/cv/PycharmProjects/vedadet/setup.py", line 146, in <module>
        'src/cuda/nms_cuda.cpp', 'src/cuda/nms_kernel.cu'
      File "/home/cv/PycharmProjects/vedadet/setup.py", line 33, in make_cuda_ext
        raise EnvironmentError('CUDA is required to compile vedadet')
    OSError: CUDA is required to compile vedadet
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
    Compiling nms_ext without CUDA
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/cv/anaconda3/envs/tinaface/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/home/cv/anaconda3/envs/tinaface/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/home/cv/anaconda3/envs/tinaface/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 324, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/cv/anaconda3/envs/tinaface/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/cv/anaconda3/envs/tinaface/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/cv/anaconda3/envs/tinaface/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 326, in _get_abstract_dist_for
    return self.preparer.prepare_editable_requirement(req)
  File "/home/cv/anaconda3/envs/tinaface/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 526, in prepare_editable_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/home/cv/anaconda3/envs/tinaface/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 91, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/home/cv/anaconda3/envs/tinaface/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/home/cv/anaconda3/envs/tinaface/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 555, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/home/cv/anaconda3/envs/tinaface/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 535, in _generate_metadata
    details=self.name or "from {}".format(self.link)
  File "/home/cv/anaconda3/envs/tinaface/lib/python3.7/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 73, in generate_metadata
    command_desc='python setup.py egg_info',
  File "/home/cv/anaconda3/envs/tinaface/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Removed file:///home/cv/PycharmProjects/vedadet from build tracker '/tmp/pip-req-tracker-mxmsm8pp'
Removed build tracker: '/tmp/pip-req-tracker-mxmsm8pp'

**Comment by hxcai** [comment]
@gmt710 please see [this](https://github.com/Media-Smart/vedadet/tree/main/configs/trainval/tinaface) for data preparing.

**Comment by hxcai** [comment]
@Kerr46 It seems that your environment has no cuda?

**Comment by gmt710** [comment]
@hxcai , Greatly Thanks. I'll try.

**Comment by gmt710** [comment]
@hxcai ,I follow  this ,also met same problem. 
Maybe parse xml do not work.

**Comment by gmt710** [comment]
@mike112223 ,Thanks. I'll try.

**Comment by gmt710** [comment]
I took some notes for reference.   https://blog.csdn.net/qq_35975447/article/details/110430390

**Comment by hxcai** [comment]
@gmt710 Great, thanks for sharing!

**Comment by gmt710** [comment]
Thanks. The result is same with your paper. I test no TTA（the result is good）：
![image](https://user-images.githubusercontent.com/34018741/100978065-d3c43480-357c-11eb-8bb8-667734b8f0c2.png)

**Comment by gmt710** [comment]
If I want to use cuda9.0, Do you have any suggestions for me to modify dcn?
I've tried the version of dcn from [mmdetection](https://github.com/open-mmlab/mmdetection) several times but fail .

**Comment by hxcai** [comment]
@hxcai You can try to use dcn in old version mmdetection that supports cuda9.0. But we don't recommend to do that.

**Comment by hxcai** [comment]
@gmt710 You can try to use dcn in old version mmdetection that supports cuda9.0. But we don't recommend to do that.

**Comment by gmt710** [comment]
@hxcai , Is this mainly because there is a corresponding relationship between torch and CUDA versions?

**Comment by hxcai** [comment]
@gmt710 specified torch and dcn implementation is related to specified cuda version.

**Comment by yehudit22** [comment]
I am still facing the same problem after doing all of what was suggested above, can anyone help?
